# This Dockerfile constructs a docker image, based on the vistalab/freesurfer
# docker image to execute recon-all as a Flywheel Gear.
#
# Example build:
#   docker build --no-cache --tag scitran/freesurfer-dev:build-stamp `pwd`


FROM ubuntu:xenial
LABEL MAINTAINER="Flywheel <support@flywheel.io>"

# Install dependencies for FreeSurfer
RUN apt-get update && apt-get -y install \
        bc \
        tar \
        zip \
        wget \
        gawk \
        tcsh \
        python \
        libgomp1 \
        python2.7 \
        python-pip \
        perl-modules \
        libxt-dev \
        libxmu-dev && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Download Freesurfer dev from MGH and untar to /opt
# This is dependent on a nightly build timestamp (/opt/freesurfer/build-stamp.txt)... rather than a git commit
RUN wget -N -qO- ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/dev/freesurfer-linux-centos6_x86_64-dev.tar.gz | tar -xz -C /opt && chown -R root:root /opt/freesurfer

# Make directory for flywheel spec (v0)
ENV FLYWHEEL /flywheel/v0
RUN mkdir -p ${FLYWHEEL}
WORKDIR ${FLYWHEEL}

# Run the run.sh script on entry.
ENTRYPOINT ["/flywheel/v0/run"]
